# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlockApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlockApp

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Kingfisher'
pod 'Toucan'
pod 'SnapKit'

end
